image: python:3.6.8
definitions:
    steps:
        - step: &build-test
            name: Build and test
            caches:
                - pip
            script:
                - pip install -r requirements.txt
                - python manage.py test --settings=${SETTINGS_MODULE}



pipelines:
    default:
        - step: *build-test

    branches:
        master:
            - step: *build-test
            - step:
                name: Deploy
                deployment: production
                script:
                    - ssh ${DEPLOY_USER}@${MASTER_SERVER} "cd ${STACK_FOLDER}${SRC_FOLDER}; git fetch;"
                    - ssh ${DEPLOY_USER}@${MASTER_SERVER} "cd ${STACK_FOLDER}${SRC_FOLDER}; git reset origin/master --hard"
                    - ssh ${DEPLOY_USER}@${MASTER_SERVER} "docker restart ${DOCKER_IMAGE}"
                    - ssh ${DEPLOY_USER}@${MASTER_SERVER} "sleep 5; docker restart ${DOCKER_NGINX_IMAGE}"

clone:
    depth: 1

options:
    max-time: 10
