# Generated by Django 2.1.7 on 2019-04-06 16:28

import backend.apps.sar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAttendees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('attendee_role', models.CharField(choices=[('organizer', 'Organizer'), ('scout', 'Scout'), ('resolver', 'Resolver')], default=backend.apps.sar.models.AttendeeRoles('Resolver'), max_length=31)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_attendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('held', 'Held')], default=backend.apps.sar.models.OperationStatuses('Scheduled'), max_length=31),
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('bambi', 'bambi'), ('firefighters', 'firefighters'), ('earthquake', 'earthquake')], default=backend.apps.sar.models.OperationTypes('bambi'), max_length=31),
        ),
        migrations.AddField(
            model_name='operationsattendees',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_attendees', to='sar.Operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='attendees',
            field=models.ManyToManyField(related_name='operations', through='sar.OperationsAttendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
