# Generated by Django 2.1.7 on 2019-04-06 18:09

import backend.apps.sar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sar', '0002_auto_20190406_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('coordinates', 'Coordinates')], default=backend.apps.sar.models.CheckedPointTypes('Drone'), max_length=31)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checked_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('coordinates', 'Coordinates')], default=backend.apps.sar.models.GeofenceTypes('Coordinates'), max_length=31)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('in_proggress', 'In Progress')], default=backend.apps.sar.models.GeofenceStatuses('Open'), max_length=31)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geotag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('drone', 'Drone'), ('mobile', 'Mobile'), ('remote', 'Remote')], default=backend.apps.sar.models.GeotagTypes('Drone'), max_length=31)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('in_proggress', 'In Progress')], default=backend.apps.sar.models.GeotagStatuses('Open'), max_length=31)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geotags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='geotag',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geotags', to='sar.Operation'),
        ),
        migrations.AddField(
            model_name='geotag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_geotags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geotag',
            name='solvers',
            field=models.ManyToManyField(related_name='geotags_to_resolve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geofence',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='sar.Operation'),
        ),
        migrations.AddField(
            model_name='checkedpoint',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_points', to='sar.Operation'),
        ),
    ]
