# Generated by Django 2.1.7 on 2019-04-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0003_auto_20190406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedpoint',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_points', to='sar.Operation'),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='sar.Operation'),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotags', to='sar.Operation'),
        ),
    ]
