# Generated by Django 2.1.7 on 2019-04-07 11:59

import backend.apps.sar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0004_auto_20190406_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('in_progress', 'In Progress')], default=backend.apps.sar.models.GeotagStatuses('Open'), max_length=31),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('bambi', 'bambi'), ('firefighters', 'Firefighters'), ('earthquake', 'Earthquake'), ('flood', 'Flood')], default=backend.apps.sar.models.OperationTypes('bambi'), max_length=31),
        ),
    ]
