# Generated by Django 2.1.7 on 2019-04-07 12:20

import backend.apps.sar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sar', '0005_auto_20190407_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('organizer', 'Organizer')], default=backend.apps.sar.models.InvitationTypes('Regular'), max_length=31)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default=backend.apps.sar.models.InvitationStatuses('Open'), max_length=31)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='sar.Operation')),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='checkedpoint',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
