# Generated by Django 2.1.7 on 2019-07-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sar', '0006_auto_20190407_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedpoint',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='geofence',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='geotag',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='operationsattendees',
            name='deleted',
        ),
    ]
