# Generated by Django 2.1.7 on 2019-07-28 13:38

import backend.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleActionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(blank=True, max_length=31, null=True)),
                ('application', models.CharField(blank=True, max_length=31, null=True)),
                ('access_level', models.CharField(choices=[('none', 'none'), ('owner', 'owner'), ('shared', 'shared'), ('admin', 'admin')], default=backend.core.models.AccessLevels('owner'), max_length=31)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleViewPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(blank=True, max_length=31, null=True)),
                ('application', models.CharField(blank=True, max_length=31, null=True)),
                ('access_level', models.CharField(choices=[('none', 'none'), ('owner', 'owner'), ('shared', 'shared'), ('admin', 'admin')], default=backend.core.models.AccessLevels('owner'), max_length=31)),
            ],
            options={
                'ordering': ['-date_modified'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='core.Role'),
        ),
    ]
